"""
Archon Configuration
====================

Configuration constants for Archon integration.
These values are used in prompts and for project state management.

Replaces linear_config.py for Archon-based task management.
"""

import os

# Environment variables
# Note: Archon uses local MCP server, no API key needed for basic connection
# The Archon server must be running (Docker containers up)
ARCHON_MCP_URL = os.environ.get("ARCHON_MCP_URL", "http://localhost:8051/mcp")

# Task status workflow (Archon uses lowercase statuses)
STATUS_TODO = "todo"
STATUS_DOING = "doing"  # Linear calls this "In Progress"
STATUS_REVIEW = "review"  # Archon-specific: for validation before done
STATUS_DONE = "done"

# Valid status values for validation
VALID_STATUSES = [STATUS_TODO, STATUS_DOING, STATUS_REVIEW, STATUS_DONE]

# Assignee options (Archon uses simple strings)
ASSIGNEE_USER = "User"
ASSIGNEE_ARCHON = "Archon"
ASSIGNEE_AI_AGENT = "AI IDE Agent"

# Task priority (Archon uses task_order: 0-100, higher = more priority)
PRIORITY_URGENT = 100  # Highest priority
PRIORITY_HIGH = 75
PRIORITY_MEDIUM = 50
PRIORITY_LOW = 25

# Document types (Archon supports structured documents)
DOC_TYPE_SPEC = "spec"
DOC_TYPE_DESIGN = "design"
DOC_TYPE_NOTE = "note"
DOC_TYPE_PRP = "prp"  # Production Requirements Prompt
DOC_TYPE_API = "api"
DOC_TYPE_GUIDE = "guide"

# Local marker file to track Archon project initialization
ARCHON_PROJECT_MARKER = ".archon_project.json"

# Meta task title for project tracking and session handoff
META_TASK_TITLE = "[META] PRD Generation Progress Tracker"

# Default pagination
DEFAULT_PAGE_SIZE = 10

# PRD-specific configuration
PRD_PROJECT_NAME = "Roofing SAAS PRD Generation"
PRD_PROJECT_DESCRIPTION = """
Production Requirements Document generation for the Roofing SAAS application.

This project tracks the systematic documentation of all features, APIs,
integrations, and technical specifications of the Roofing SAAS platform.

Generated by the autonomous PRD harness using Archon for task management
and the Archon knowledge base for reference documentation.
"""

# Feature labels for PRD tasks
FEATURE_OVERVIEW = "overview"
FEATURE_AUTH = "authentication"
FEATURE_CONTACTS = "contacts"
FEATURE_PROJECTS = "projects"
FEATURE_PIPELINE = "pipeline"
FEATURE_COMMUNICATIONS = "communications"
FEATURE_INTEGRATIONS = "integrations"
FEATURE_MOBILE = "mobile-pwa"
FEATURE_GAMIFICATION = "gamification"
FEATURE_VOICE = "voice-assistant"
FEATURE_API = "api-reference"
FEATURE_DATA = "data-models"
FEATURE_SECURITY = "security"
