"""
Modernization Analysis Configuration
=====================================

Configuration constants for modernization analysis harness.
These values are used in prompts and for project state management.

Based on archon_config.py but adapted for modernization workflow.
"""

import os

# Environment variables
# Note: Archon uses local MCP server, no API key needed for basic connection
# The Archon server must be running (Docker containers up)
ARCHON_MCP_URL = os.environ.get("ARCHON_MCP_URL", "http://localhost:8051/mcp")

# Task status workflow (Archon uses lowercase statuses)
STATUS_TODO = "todo"
STATUS_DOING = "doing"
STATUS_REVIEW = "review"  # Archon-specific: for validation before done
STATUS_DONE = "done"

# Valid status values for validation
VALID_STATUSES = [STATUS_TODO, STATUS_DOING, STATUS_REVIEW, STATUS_DONE]

# Assignee options (Archon uses simple strings)
ASSIGNEE_USER = "User"
ASSIGNEE_ARCHON = "Archon"
ASSIGNEE_AI_AGENT = "AI IDE Agent"

# Task priority (Archon uses task_order: 0-100, higher = more priority)
PRIORITY_URGENT = 100  # Highest priority
PRIORITY_HIGH = 75
PRIORITY_MEDIUM = 50
PRIORITY_LOW = 25

# Document types (Archon supports structured documents)
DOC_TYPE_MODERNIZATION = "modernization"
DOC_TYPE_ANALYSIS = "analysis"
DOC_TYPE_COMPARISON = "comparison"
DOC_TYPE_RECOMMENDATION = "recommendation"

# Local marker file to track modernization project initialization
MODERNIZATION_MARKER = ".modernization_project.json"

# Meta task title for project tracking and session handoff
META_TASK_TITLE = "[META] Modernization Analysis Progress Tracker"

# Default pagination
DEFAULT_PAGE_SIZE = 10

# Modernization-specific configuration
MODERNIZATION_PROJECT_NAME = "Roofing SAAS Modernization Analysis"
MODERNIZATION_PROJECT_DESCRIPTION = """
Modernization and innovation analysis for the Roofing SAAS application.

This project systematically reviews the existing PRD and codebase to:
- Identify discrepancies between documentation and code
- Challenge architectural decisions
- Research modern alternatives
- Compare current stack vs modern options (Sept → Dec 2025)
- Recommend innovations and improvements

Generated by the autonomous modernization harness using Archon for task management,
Puppeteer for web research, and the Archon knowledge base for reference documentation.
"""

# Path configuration
PRD_SOURCE_DIR = "/Users/ccai/roofing saas/roofing-saas/docs/PRD"
SOURCE_CODE_DIR = "/Users/ccai/roofing saas/roofing-saas"
OUTPUT_DIR = "/Users/ccai/roofing saas/roofing-saas/docs/modernization-analysis"

# Research configuration
MIN_RESEARCH_SITES = 5  # Minimum websites to visit per section
MIN_SCREENSHOTS = 5  # Minimum screenshots to capture per section
MIN_DEVIL_ADVOCATE_QUESTIONS = 3  # Minimum assumptions to challenge per section

# Research URL templates (common starting points)
RESEARCH_URLS = {
    "react": "https://react.dev",
    "nextjs": "https://nextjs.org",
    "supabase": "https://supabase.com/docs",
    "vercel": "https://vercel.com/docs",
    "typescript": "https://www.typescriptlang.org",
    "tailwind": "https://tailwindcss.com",
    "shadcn": "https://ui.shadcn.com",
    "playwright": "https://playwright.dev",
    "astro": "https://astro.build",
    "remix": "https://remix.run",
    "convex": "https://www.convex.dev",
    "planetscale": "https://planetscale.com",
    "turso": "https://turso.tech",
}

# Feature labels (same as PRD for consistency)
FEATURE_OVERVIEW = "overview"
FEATURE_AUTH = "authentication"
FEATURE_CONTACTS = "contacts"
FEATURE_PROJECTS = "projects"
FEATURE_PIPELINE = "pipeline"
FEATURE_COMMUNICATIONS = "communications"
FEATURE_INTEGRATIONS = "integrations"
FEATURE_MOBILE = "mobile-pwa"
FEATURE_GAMIFICATION = "gamification"
FEATURE_VOICE = "voice-assistant"
FEATURE_API = "api-reference"
FEATURE_DATA = "data-models"
FEATURE_SECURITY = "security"
