apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Remove eslint-disable comments that were added as shortcuts and fix the\n\
    underlying code issues properly.\n\nFiles with shortcuts to fix:\n\n1. app/(dashboard)/insights/insights-client.tsx\n\
    \   - Line 41: eslint-disable-next-line react-hooks/exhaustive-deps\n   - Fix:\
    \ Wrap loadSuggestions and loadQueryHistory in useCallback, add to deps\n\n2.\
    \ components/automation/WorkflowCanvas.tsx\n   - Line 106: eslint-disable-next-line\
    \ @typescript-eslint/no-explicit-any\n   - Fix: Create proper ActionConfig interface\
    \ for workflow action configs\n\n3. lib/realtime/channel-manager.ts\n   - Line\
    \ 572: eslint-disable-next-line @typescript-eslint/no-explicit-any\n   - Fix:\
    \ Create SupabasePresencePayload interface for presence callbacks\n\nProper Fixes\
    \ Required:\n\nFor useEffect dependencies:\n```typescript\nconst loadSuggestions\
    \ = useCallback(async () => {\n  // existing code\n}, [userRole, tenantId])\n\n\
    const loadQueryHistory = useCallback(async () => {\n  // existing code\n}, [tenantId,\
    \ userId])\n\nuseEffect(() => {\n  loadSuggestions()\n  loadQueryHistory()\n},\
    \ [loadSuggestions, loadQueryHistory])\n```\n\nFor any types - create interfaces:\n\
    ```typescript\ninterface SupabasePresencePayload {\n  userId: string\n  userName:\
    \ string\n  userEmail: string\n  userAvatar?: string\n  joinedAt: string\n  metadata?:\
    \ Record<string, unknown>\n}\n```\n"
  success_criteria:
  - No eslint-disable comments in the three specified files
  - useEffect in insights-client.tsx has correct dependencies
  - Proper TypeScript interfaces replace all `any` types
  - npm run lint passes with 0 warnings in modified files
  - npm run typecheck passes
  why: 'ESLint warnings exist for a reason. Suppressing them without fixing the

    underlying issue is technical debt that compounds over time.


    - react-hooks/exhaustive-deps prevents stale closure bugs

    - no-explicit-any ensures type safety throughout the codebase


    These shortcuts were added to unblock a commit, but the proper fix should

    have been done from the start. This task corrects that mistake.

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T09:00:00'
  id: CLEANUP-001
  priority: 2
  template: code-modification
  title: Remove ESLint Shortcuts - Fix Code Properly
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git checkout -- app/(dashboard)/insights/insights-client.tsx
  - git checkout -- components/automation/WorkflowCanvas.tsx
  - git checkout -- lib/realtime/channel-manager.ts
read_first:
- extract: []
  path: app/(dashboard)/insights/insights-client.tsx
  reason: Understand the useEffect pattern and what needs useCallback
  required: true
- extract: []
  path: lib/realtime/channel-manager.ts
  reason: Understand Supabase presence callback structure
  required: true
- extract: []
  path: components/automation/WorkflowCanvas.tsx
  reason: Understand workflow action config structure
  required: true
- extract: []
  path: lib/automation/workflow-types.ts
  reason: Existing workflow type definitions
  required: true
scope:
  constraints: []
  create:
  - lib/types/supabase-presence.ts
  do_not_touch:
  - Any files not listed above
  - Test files
  modify:
  - app/(dashboard)/insights/insights-client.tsx
  - components/automation/WorkflowCanvas.tsx
  - lib/realtime/channel-manager.ts
thinking:
  level: think
  triggers:
  - When designing the presence payload interface
  - When restructuring useEffect dependencies
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: grep -r 'eslint-disable' app/(dashboard)/insights/insights-client.tsx
      components/automation/WorkflowCanvas.tsx lib/realtime/channel-manager.ts | wc
      -l
    expect: 'output: 0'
    required: true
    timeout: 60
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint -- --max-warnings 0
    expect: 'exit_code: 0'
    required: true
    timeout: 60
