apiVersion: aces/v1
changes: []
context:
  background: null
  goal: Preview templates before using them to create documents
  success_criteria:
  - Template list shows preview button for each template
  - Preview modal displays template PDF
  - Field positions shown as overlays on preview
  - Field types indicated such as signature initials date
  - Use This Template button in preview
  - Template selection in new document flow shows inline previews
  - Preview loads quickly via lazy load PDF
  why: Users create documents blind - no way to see template PDF or field positions
    before selecting
dependencies: null
handoff:
  format: null
  progress_file: .vest/phase-2.3-progress.md
  update_on:
  - task_start
  - validation_passed
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: null
  id: ESIG-PREVIEW-23
  priority: 3
  template: null
  title: Template Preview Before Using
on_failure:
  escalate: null
  rollback:
  - git checkout -- app/(dashboard)/signatures/templates/page.tsx
  - git checkout -- app/(dashboard)/signatures/new/page.tsx
read_first:
- extract: []
  path: app/(dashboard)/signatures/templates/page.tsx
  reason: Understand current template list page structure
  required: true
- extract: []
  path: app/(dashboard)/signatures/new/page.tsx
  reason: See current document creation flow with template selection
  required: true
- extract: []
  path: components/signatures/DocumentEditor.tsx
  reason: Reference for rendering PDF with field overlays
  required: true
- extract: []
  path: components/ui/dialog.tsx
  reason: Use Dialog component for preview modal
  required: false
scope:
  constraints: []
  create: []
  do_not_touch:
  - app/sign/**/*
  - components/signatures/DocumentEditor.tsx
  - app/api/signature-templates/**/*
  - lib/auth/**/*
  modify:
  - app/(dashboard)/signatures/templates/page.tsx
  - app/(dashboard)/signatures/new/page.tsx
thinking: null
validation:
  assertions: []
  post_commit:
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint
    expect: 'exit_code: 0'
    required: true
    timeout: 60
