apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Fix all remaining ESLint warnings and errors across the codebase to achieve\n\
    zero-warning compliance. This is transitional cleanup of harness-generated\nSprint\
    \ 5 code that was created before the strict validation policy.\n\nCurrent State\
    \ (98 files, 536 issues):\n- 187 @typescript-eslint/no-explicit-any warnings\n\
    - 149 @typescript-eslint/no-unused-vars warnings\n- 8 react-hooks/exhaustive-deps\
    \ warnings\n- Various other issues\n\nIssue Categories and Fixes:\n\n1. NO-EXPLICIT-ANY\
    \ (187 issues)\n   Pattern: Replace `any` with proper types\n\n   Common patterns\
    \ to fix:\n   - Function parameters: `(data: any)` -> `(data: Record<string, unknown>)`\n\
    \   - API responses: `response.json() as any` -> proper interface\n   - Event\
    \ handlers: `(e: any)` -> `(e: React.ChangeEvent<HTMLInputElement>)`\n   - Supabase\
    \ data: Add proper table row types\n\n   Strategy:\n   - Create interfaces for\
    \ repeated patterns\n   - Use `unknown` with type guards for truly dynamic data\n\
    \   - Use generics where appropriate\n\n2. NO-UNUSED-VARS (149 issues)\n   Pattern:\
    \ Remove unused imports and variables\n\n   Fixes:\n   - Remove unused imports\n\
    \   - Prefix intentionally unused params with underscore: `_param`\n   - Remove\
    \ dead code\n\n3. REACT-HOOKS/EXHAUSTIVE-DEPS (8 issues)\n   Pattern: Fix useEffect/useCallback\
    \ dependencies\n\n   Fixes:\n   - Add missing dependencies\n   - Wrap callbacks\
    \ in useCallback\n   - Use refs for values that shouldn't trigger re-renders\n\
    \nFile Categories (prioritized):\n\nHIGH PRIORITY (Core functionality):\n- lib/offline/*.ts\
    \ (5 files) - PWA/offline infrastructure\n- lib/dashboard/*.tsx (2 files) - Dashboard\
    \ components\n- app/api/**/*.ts (12 files) - API routes\n- components/ar/*.tsx\
    \ (4 files) - AR assessment\n\nMEDIUM PRIORITY (Feature pages):\n- app/(dashboard)/**/*.tsx\
    \ - Dashboard pages\n- app/[locale]/**/*.tsx - Internationalized pages\n\nApproach:\n\
    - Fix by module/feature area, not file-by-file\n- Create shared type definitions\
    \ in lib/types/\n- Run lint after each module to verify progress\n- Commit incrementally\
    \ if needed\n"
  success_criteria:
  - npm run lint -- --max-warnings 0 passes
  - npm run typecheck passes
  - No eslint-disable comments added (fix underlying issues)
  - All 98 files with issues are clean
  why: 'This is the final cleanup of transitional code from Sprint 5 harness output.


    The Sprint 5 tasks (AR, PWA, Dashboard, i18n, Marketplace) were executed

    before IMPROVEMENT-002 enforced --max-warnings 0. As a result, they

    produced code with `any` types and other lint issues.


    After this task:

    - Codebase will have zero lint warnings

    - All future harness output will be held to the same standard

    - Pre-commit hooks will pass without --no-verify

    - Clean baseline for ongoing development

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T10:00:00'
  id: CLEANUP-003
  priority: 2
  template: code-modification
  title: Fix All Remaining Lint Issues - Sprint 5 Transitional Cleanup
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    - remaining_lint_issues
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: lib/offline/offline-types.ts
  reason: Understand existing offline type definitions
  required: true
- extract: []
  path: lib/types/supabase-presence.ts
  reason: Pattern for creating proper type definitions
  required: true
- extract: []
  path: tsconfig.json
  reason: TypeScript configuration
  required: false
scope:
  constraints: []
  create:
  - lib/types/api-responses.ts
  - lib/types/offline-types.ts
  - lib/types/ar-types.ts
  do_not_touch:
  - node_modules/
  - .next/
  - Test files unless they have issues
  modify:
  - lib/offline/indexed-db.ts
  - lib/offline/sync-manager.ts
  - lib/offline/cache-strategy.ts
  - lib/offline/offline-types.ts
  - lib/offline/conflict-resolution.ts
  - lib/dashboard/DashboardEditor.tsx
  - lib/dashboard/examples/dashboard-usage-example.tsx
  - components/ar/ARViewport.tsx
  - components/ar/ARToolbar.tsx
  - components/ar/MeasurementOverlay.tsx
  - components/ar/DamageMarker.tsx
  - app/api/admin/audit-log/route.ts
  - app/api/admin/audit-log/export/route.ts
  - app/api/analytics/forecast/route.ts
  - app/api/analytics/pipeline/route.ts
  - app/api/ar/measurements/route.ts
  - app/api/automations/route.ts
  - app/api/contacts/[id]/route.ts
  - app/api/contacts/[id]/score/route.ts
  - app/api/estimates/[id]/options/route.ts
  - app/api/insights/query/route.ts
  - app/api/storm/notifications/route.ts
  - app/api/storm/predictions/route.ts
  - app/api/sync/route.ts
  - app/(dashboard)/automations/[id]/page.tsx
  - app/(dashboard)/automations/new/page.tsx
  - app/(dashboard)/automations/page.tsx
  - app/[locale]/(dashboard)/automations/[id]/page.tsx
  - app/[locale]/(dashboard)/automations/new/page.tsx
  - app/[locale]/(dashboard)/automations/page.tsx
  - app/(dashboard)/contacts/[id]/ContactDetailClient.tsx
  - app/(dashboard)/dashboard/edit/page.tsx
  - app/(dashboard)/pipeline/analytics/page.tsx
  - app/(dashboard)/projects/[id]/ar-assessment/page.tsx
  - app/(dashboard)/projects/[id]/page.tsx
  - app/(dashboard)/settings/scoring/ScoringSettingsClient.tsx
  - app/(dashboard)/storm-tracking/page.tsx
thinking:
  level: think_hard
  triggers:
  - When designing shared type definitions
  - When fixing complex generic patterns
  - When deciding between unknown and specific types
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run lint -- --max-warnings 0
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
