apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Implement advanced pipeline analytics with conversion funnels,\nvelocity\
    \ tracking, and predictive forecasting.\n\nFeatures to implement:\n1. Visual conversion\
    \ funnel with drop-off analysis\n2. Pipeline velocity metrics (days in each stage)\n\
    3. Win/loss analysis with reasons\n4. Revenue forecasting based on pipeline\n\
    5. Team performance comparisons\n\nKey Metrics:\n- Stage conversion rates\n- Average\
    \ time in each stage\n- Pipeline velocity trend\n- Win rate by lead source\n-\
    \ Lost deal reasons distribution\n- Revenue forecast (30/60/90 day)\n\nVisualization\
    \ Types:\n- Funnel chart (stage progression)\n- Trend lines (velocity over time)\n\
    - Heatmap (bottleneck identification)\n- Cohort analysis (lead source performance)\n\
    \nDrill-Down Capabilities:\n- Click funnel stage \u2192 See deals\n- Click metric\
    \ \u2192 See underlying data\n- Filter by date, rep, source\n"
  success_criteria:
  - Conversion funnel visualizes correctly
  - Pipeline velocity calculates accurately
  - Forecasting uses historical data
  - Drill-down shows underlying deals
  - Date range filtering works
  why: 'Research Finding: Pipeline exists but lacks analytics.

    Industry Need: Data-driven sales optimization.


    Business Impact:

    - Identify bottlenecks before they hurt revenue

    - 15% improvement in conversion through optimization

    - Better sales forecasting accuracy

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T19:00:00'
  id: SPRINT4-004
  priority: 3
  template: code-modification
  title: Advanced Pipeline Analytics
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: components/pipeline/PipelineBoard.tsx
  reason: Pipeline structure and data
  required: true
- extract: []
  path: app/(dashboard)/pipeline/page.tsx
  reason: Pipeline page for analytics link
  required: true
- extract: []
  path: lib/types/pipeline.ts
  reason: Pipeline type definitions
  required: false
scope:
  constraints: []
  create:
  - lib/analytics/pipeline-analytics.ts
  - lib/analytics/forecasting.ts
  - lib/analytics/analytics-types.ts
  - components/analytics/ConversionFunnel.tsx
  - components/analytics/VelocityChart.tsx
  - components/analytics/WinLossAnalysis.tsx
  - components/analytics/RevenueForcast.tsx
  - components/analytics/PipelineInsights.tsx
  - app/(dashboard)/pipeline/analytics/page.tsx
  - app/api/analytics/pipeline/route.ts
  - app/api/analytics/forecast/route.ts
  do_not_touch:
  - app/api/pipeline/route.ts
  - components/pipeline/PipelineColumn.tsx
  modify:
  - app/(dashboard)/pipeline/page.tsx
  - components/pipeline/PipelineBoard.tsx
thinking:
  level: think_hard
  triggers:
  - Before designing analytics calculations
  - When planning forecasting algorithm
  - When optimizing query performance
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/analytics/pipeline-analytics.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/analytics/ConversionFunnel.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f app/(dashboard)/pipeline/analytics/page.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
