apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Fix the dashboard loading issue where metrics widgets show skeleton placeholders
    indefinitely.

    The root cause is that API errors fail silently - the component doesn''t check
    response.ok before

    parsing JSON, so if the API returns 401/403/500, the component stays in loading
    state forever.


    Changes needed:

    1. DashboardMetrics.tsx: Add response.ok check, timeout handling, user-visible
    error state with retry

    2. ActivityFeed.tsx: Same fixes - add response.ok check and error state

    3. WeeklyChallengeWidget.tsx: Same fixes - add response.ok check and error state


    The error state should show a clear message and a "Retry" button, not just log
    to console.

    '
  success_criteria:
  - DashboardMetrics.tsx checks response.ok before JSON parsing
  - DashboardMetrics.tsx shows user-visible error with retry button when API fails
  - DashboardMetrics.tsx has timeout handling (30s max)
  - ActivityFeed.tsx has same error handling improvements
  - WeeklyChallengeWidget.tsx has same error handling improvements
  - No silent failures - all errors visible to users
  why: 'Smoke tests revealed the dashboard shows skeleton placeholders indefinitely
    on production.

    Users see a broken dashboard with no indication of what went wrong. This is a
    critical UX issue.

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T15:30:00'
  id: FIX-001
  priority: 3
  template: code-modification
  title: Fix Dashboard Error Handling - Prevent Silent Failures
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    - partial_progress
    to: human
  rollback:
  - git checkout -- components/dashboard/
read_first:
- extract: []
  path: components/dashboard/DashboardMetrics.tsx
  reason: Main component to fix - understand current fetch logic
  required: true
- extract: []
  path: components/dashboard/ActivityFeed.tsx
  reason: Secondary component needing same fix
  required: true
- extract: []
  path: components/dashboard/WeeklyChallengeWidget.tsx
  reason: Third component needing same fix
  required: true
- extract: []
  path: components/ui/button.tsx
  reason: Use existing Button component for retry
  required: false
scope:
  constraints:
  - Only modify the specified component files
  - Keep existing functionality intact
  - Add error handling without breaking happy path
  - Use existing UI patterns for error states
  create: []
  do_not_touch:
  - app/api/**
  - lib/**
  modify:
  - components/dashboard/DashboardMetrics.tsx
  - components/dashboard/ActivityFeed.tsx
  - components/dashboard/WeeklyChallengeWidget.tsx
thinking:
  level: think_hard
  triggers:
  - Before modifying fetch logic
  - When designing error state UI
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint
    expect: 'exit_code: 0'
    required: false
    timeout: 60
