apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Fix 149 theme-compliance errors across 8 files.\nAll hardcoded Tailwind colors\
    \ must be replaced with theme-aware CSS variables\nto support dark mode and maintain\
    \ UI consistency.\n\nAffected Files (8 total, 149 errors):\n1. app/[locale]/(dashboard)/contacts/[id]/page.tsx\n\
    2. app/[locale]/(dashboard)/financial/commissions/add-commission-button.tsx\n\
    3. app/[locale]/(dashboard)/financial/commissions/add-commission-dialog.tsx\n\
    4. app/[locale]/(dashboard)/financial/reports/margin-by-type-chart.tsx\n5. app/[locale]/(dashboard)/projects/[id]/costing/add-expense-button.tsx\n\
    6. app/[locale]/(dashboard)/projects/[id]/costing/add-expense-dialog.tsx\n7. components/ar/ARToolbar.tsx\n\
    8. components/ar/MeasurementOverlay.tsx\n\nColor Mapping (use EXACTLY these replacements):\n\
    BACKGROUNDS:\n- bg-white \u2192 bg-card or bg-background\n- bg-gray-50 \u2192\
    \ bg-muted/30 or bg-background\n- bg-gray-100 \u2192 bg-muted\n- bg-gray-200 \u2192\
    \ bg-muted\n- bg-blue-50 \u2192 bg-primary/10\n- bg-blue-100 \u2192 bg-primary/20\n\
    - bg-blue-600 \u2192 bg-primary\n- bg-purple-100 \u2192 bg-secondary/20\n\nTEXT:\n\
    - text-gray-900 \u2192 text-foreground\n- text-gray-700 \u2192 text-foreground\n\
    - text-gray-600 \u2192 text-muted-foreground\n- text-gray-500 \u2192 text-muted-foreground\n\
    - text-gray-400 \u2192 text-muted-foreground/70\n- text-blue-600 \u2192 text-primary\n\
    - text-blue-800 \u2192 text-primary\n- text-purple-800 \u2192 text-secondary-foreground\n\
    \nBORDERS:\n- border-gray-200 \u2192 border-border\n- border-gray-300 \u2192 border-border\n\
    - border-blue-600 \u2192 border-primary\n\nHOVER:\n- hover:bg-gray-50 \u2192 hover:bg-muted/50\n\
    - hover:bg-gray-100 \u2192 hover:bg-muted\n- hover:bg-blue-700 \u2192 hover:bg-primary/90\n"
  success_criteria:
  - Zero theme-compliance errors after completion
  - All 8 affected files modified
  - TypeScript compilation passes
  - Build succeeds
  why: 'Theme-compliance plugin added Dec 12. Sprint 5 harness ran Dec 14-15 without

    enforcement, generating 149 hardcoded color violations.


    These must be fixed to:

    1. Enable dark mode support

    2. Pass pre-commit lint checks

    3. Maintain consistent theming

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T10:00:00'
  id: CLEANUP-004
  priority: 2
  template: code-modification
  title: Fix Theme Compliance - Replace Hardcoded Colors
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: app/[locale]/(dashboard)/contacts/[id]/page.tsx
  reason: Largest file - understand the pattern
  required: true
- extract: []
  path: components/ar/ARToolbar.tsx
  reason: AR component with many violations
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - app/api/**
  - lib/**
  - components/ui/**
  modify:
  - app/[locale]/(dashboard)/contacts/[id]/page.tsx
  - app/[locale]/(dashboard)/financial/commissions/add-commission-button.tsx
  - app/[locale]/(dashboard)/financial/commissions/add-commission-dialog.tsx
  - app/[locale]/(dashboard)/financial/reports/margin-by-type-chart.tsx
  - app/[locale]/(dashboard)/projects/[id]/costing/add-expense-button.tsx
  - app/[locale]/(dashboard)/projects/[id]/costing/add-expense-dialog.tsx
  - components/ar/ARToolbar.tsx
  - components/ar/MeasurementOverlay.tsx
thinking:
  level: think
  triggers:
  - When processing files with semantic colors (status indicators)
  - When unsure about correct replacement
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint -- --quiet 2>&1 | grep -c 'theme-compliance' || echo 0
    expect: 'output: 0'
    required: true
    timeout: 60
