apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Enhance the existing storm tracking with predictive intelligence and\nautomated\
    \ opportunity generation for storm damage work.\n\nFeatures to implement:\n1.\
    \ Predictive storm path modeling\n2. Automatic lead generation for affected areas\n\
    3. Storm severity assessment\n4. Customer notification automation\n5. Crew pre-positioning\
    \ recommendations\n\nStorm Data Sources:\n- NOAA weather API\n- National Weather\
    \ Service alerts\n- Historical hail damage data\n- Existing customer location\
    \ data\n\nAutomation Triggers:\n- Severe storm warning \u2192 Alert sales team\n\
    - Hail event \u2192 Generate affected customer list\n- Storm passes \u2192 Send\
    \ check-in emails to customers\n- Major event \u2192 Activate storm response mode\n\
    \nIntelligence Features:\n- Damage probability by location\n- Optimal canvassing\
    \ routes\n- Historical storm damage patterns\n- Crew capacity planning\n"
  success_criteria:
  - Storm alerts trigger automatic workflows
  - Affected customer list generates automatically
  - Damage probability displays on map
  - Notification templates send on storm events
  - Historical storm data informs predictions
  why: 'Research Finding: Basic storm tracking exists but underutilized.

    Opportunity: Roofing is weather-dependent, intelligence creates advantage.


    Business Impact:

    - First-mover advantage after storms

    - 300% increase in storm-related leads

    - Better customer service (proactive outreach)

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T19:00:00'
  id: SPRINT4-003
  priority: 2
  template: code-modification
  title: Storm Intelligence Enhancement
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: app/(dashboard)/storm-tracking/page.tsx
  reason: Existing storm tracking implementation
  required: true
- extract: []
  path: components/storm/StormMap.tsx
  reason: Map component for enhancements
  required: true
- extract: []
  path: lib/integrations/weather-api.ts
  reason: Weather API integration
  required: false
scope:
  constraints: []
  create:
  - lib/storm/storm-intelligence.ts
  - lib/storm/damage-predictor.ts
  - lib/storm/storm-types.ts
  - components/storm/StormAlertPanel.tsx
  - components/storm/AffectedCustomers.tsx
  - components/storm/DamageProbability.tsx
  - components/storm/StormResponseMode.tsx
  - app/api/storm/predictions/route.ts
  - app/api/storm/affected-customers/route.ts
  - app/api/storm/notifications/route.ts
  do_not_touch:
  - lib/integrations/weather-api.ts
  modify:
  - app/(dashboard)/storm-tracking/page.tsx
  - components/storm/StormMap.tsx
thinking:
  level: ultrathink
  triggers:
  - Before designing prediction algorithm
  - When planning automation workflows
  - When optimizing real-time data handling
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/storm/storm-intelligence.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/storm/StormAlertPanel.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: grep -q "StormAlertPanel" app/(dashboard)/storm-tracking/page.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
