apiVersion: aces/v1
changes: []
context:
  background: 'Add UI for users to switch navigation styles and comprehensive testing.


    Settings UI:

    1. Add to Settings page or preferences modal

    2. Radio/toggle: Traditional | Instagram-style

    3. Preview or description of each


    Testing:

    1. Unit tests for new components

    2. Integration test for style switching

    3. Mobile viewport testing

    4. Accessibility audit (WCAG AA)


    Files:

    - app/(app)/settings/page.tsx or similar

    - tests/unit/components/layout/*.test.tsx


    **From VEST Learnings:**

    - TIP: ''eslint:no-unused-vars'' is common. Consider running: eslint --fix

    - TIP: ''unused-variable'' is common. Consider running: eslint --fix'
  goal: Add UI for users to switch navigation styles and comprehensive testing
  success_criteria:
  - Component renders correctly
  - All props and states work as expected
  - Component follows design system
  - TypeScript compilation succeeds
  - Linting passes with no warnings
  - Build process completes successfully
  - '[LEARNING] Pattern ''eslint:no-unused-vars'' occurs frequently - consider: eslint
    --fix'
  - '[LEARNING] Pattern ''unused-variable'' occurs frequently - consider: eslint --fix'
  why: 'Settings UI:

    1. Add to Settings page or preferences modal

    2. Radio/toggle: Traditional | Instagram-style

    3. Preview or description of each


    Testing:

    1. Unit tests for new components

    2. Integration test for style switching

    3. Mobile viewport testing

    4. Accessibility audit (WCAG AA)


    Files:

    - app/(app)/settings/page.tsx or similar

    - tests/unit/components/layout/*.test.tsx'
dependencies: null
handoff: null
kind: TaskSpec
metadata:
  archon_task_id: 1fd146de-f675-48b8-acbc-cf1ee1d09847
  created: '2025-12-19T19:39:53.270365'
  id: 1FD146DE-IGNAV008001
  priority: 2
  template: react-component
  title: 'IG-NAV-008: Add navStyle toggle to settings + testing'
on_failure: null
read_first:
- extract: []
  path: README.md
  reason: Understanding project structure and conventions
  required: true
- extract: []
  path: tsconfig.json
  reason: Understanding TypeScript configuration
  required: false
- extract: []
  path: src/components/index.ts
  reason: Understanding component architecture
  required: false
scope:
  auto_rollback: false
  constraints:
  - Follow existing code patterns
  - Maintain TypeScript compliance
  - Do not break existing functionality
  create:
  - src/components/**/*.tsx
  - src/components/**/*.ts
  - '**/*.test.tsx'
  do_not_touch:
  - package.json
  - package-lock.json
  - yarn.lock
  - .git/**
  - node_modules/**
  - dist/**
  - build/**
  - /Users/ccai/Projects/VEST/**
  - /Users/ccai/Projects/VEST/vest/**
  - /Users/ccai/Projects/VEST/run_aces.py
  - /Users/ccai/Projects/VEST/variants/**
  - /Users/ccai/Projects/VEST/harness/**
  - /Users/ccai/Projects/VEST/SPEC.md
  - /Users/ccai/Projects/VEST/PROTOCOL.md
  modify:
  - src/components/**/*.tsx
  - src/components/**/*.ts
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 180
