apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Implement a comprehensive audit trail system for compliance and

    data change tracking across the application.


    Features to implement:

    1. Track all CRUD operations with user attribution

    2. Store before/after values for all changes

    3. Audit log viewer in admin panel

    4. Compliance reports (who changed what, when)

    5. Data retention policy management


    What to Track:

    - Contact changes (all fields)

    - Project status changes

    - Estimate modifications

    - User permission changes

    - Settings changes

    - Document access


    Audit Entry Structure:

    - Timestamp

    - User ID and name

    - Action type (create/update/delete)

    - Entity type and ID

    - Before/after JSON diff

    - IP address and user agent

    '
  success_criteria:
  - All entity changes are logged automatically
  - Audit log viewer shows history with filters
  - Can export audit reports
  - Before/after values are captured
  - Performance impact is minimal
  why: 'Research Finding: Only admin impersonation tracking exists.

    Compliance Need: Complete data change tracking for regulatory requirements.


    Business Impact:

    - Reduced compliance risk

    - Enables troubleshooting and rollback

    - Required for enterprise customers

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T19:00:00'
  id: SPRINT3-005
  priority: 2
  template: code-modification
  title: Comprehensive Audit Trail
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: app/api/contacts/route.ts
  reason: API route pattern to add audit logging
  required: true
- extract: []
  path: app/api/contacts/[id]/route.ts
  reason: Update/delete patterns for audit
  required: true
- extract: []
  path: lib/auth/session.ts
  reason: User context for audit entries
  required: true
scope:
  constraints: []
  create:
  - lib/audit/audit-logger.ts
  - lib/audit/audit-types.ts
  - lib/audit/audit-middleware.ts
  - app/(dashboard)/admin/audit-log/page.tsx
  - components/admin/AuditLogTable.tsx
  - components/admin/AuditLogFilters.tsx
  - components/admin/AuditEntryDetail.tsx
  - app/api/admin/audit-log/route.ts
  - app/api/admin/audit-log/export/route.ts
  do_not_touch:
  - lib/supabase/server.ts
  - database migrations
  modify:
  - app/api/contacts/route.ts
  - app/api/contacts/[id]/route.ts
  - app/api/projects/route.ts
  - app/api/projects/[id]/route.ts
thinking:
  level: think_hard
  triggers:
  - Before designing audit log schema
  - When planning middleware integration
  - When optimizing storage strategy
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/audit/audit-logger.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f app/(dashboard)/admin/audit-log/page.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: grep -q "auditLog" app/api/contacts/route.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
