apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Implement dark mode theme support with system preference detection

    and manual toggle capability.


    Features to implement:

    1. Dark mode color scheme following design system

    2. System preference detection (prefers-color-scheme)

    3. Manual theme toggle in settings

    4. Persist user preference

    5. Smooth theme transition animations


    Technical Approach:

    - Use Tailwind CSS dark mode (class strategy)

    - Theme provider with next-themes

    - Update all hardcoded colors to use CSS variables

    - Ensure all components respect theme


    Color Mapping:

    - bg-background, bg-card (light/dark variants)

    - text-foreground, text-muted-foreground

    - border-border

    - Ensure proper contrast ratios in both modes


    NOTE: This builds on SPRINT2-003 UI Consistency work.

    Many hardcoded colors should already be fixed.

    '
  success_criteria:
  - Dark mode toggle works in settings
  - System preference is detected on first visit
  - All pages render correctly in dark mode
  - Charts and graphs respect dark theme
  - No contrast issues or illegible text
  - Preference persists across sessions
  why: 'Research Finding: Dark mode is standard expectation in 2024 SaaS.

    User Impact: Reduced eye strain, modern aesthetic appeal.


    Business Impact:

    - Improved user satisfaction

    - Reduced eye strain for heavy users

    - Modern, professional appearance

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T19:00:00'
  id: SPRINT3-006
  priority: 3
  template: code-modification
  title: Dark Mode Theme Support
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: tailwind.config.ts
  reason: Tailwind dark mode configuration
  required: true
- extract: []
  path: app/layout.tsx
  reason: Root layout for theme provider
  required: true
- extract: []
  path: globals.css
  reason: Global styles and CSS variables
  required: true
scope:
  constraints: []
  create:
  - components/theme/ThemeProvider.tsx
  - components/theme/ThemeToggle.tsx
  - lib/hooks/useTheme.ts
  - styles/themes/dark.css
  do_not_touch:
  - components/ui/button.tsx
  - components/ui/input.tsx
  modify:
  - app/layout.tsx
  - app/(dashboard)/layout.tsx
  - tailwind.config.ts
  - components/settings/appearance-settings.tsx
thinking:
  level: think
  triggers:
  - Before planning CSS variable structure
  - When auditing components for theme compliance
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/theme/ThemeProvider.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/theme/ThemeToggle.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: grep -q "ThemeProvider" app/layout.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
