apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Refactor the contact form from vanilla useState (25+ state declarations)

    to React Hook Form with Zod validation. This improves performance,

    maintainability, and enables field-level validation.

    '
  success_criteria:
  - Contact form uses useForm() hook
  - Zod schema for validation
  - All 35+ fields properly managed
  - No functional regressions
  why: Technical debt - contact form uses inefficient vanilla React state pattern
dependencies: null
handoff:
  format: null
  progress_file: .vest/quickwin-004-progress.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T00:00:00'
  id: QUICKWIN-004
  priority: 2
  template: refactor
  title: Migrate Contact Form to React Hook Form
on_failure:
  escalate:
    include:
    - error_output
    to: human
  rollback:
  - git checkout -- components/contacts/contact-form.tsx
read_first:
- extract: []
  path: components/contacts/contact-form.tsx
  reason: Current form implementation with useState
  required: true
- extract: []
  path: lib/validations/contact.ts
  reason: Existing Zod schema to reuse
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - lib/**
  - app/api/**
  modify:
  - components/contacts/contact-form.tsx
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint
    expect: 'exit_code: 0'
    required: true
    timeout: 60
