apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Implement Multi-Factor Authentication (MFA) for admin accounts using

    Supabase TOTP MFA. This addresses a security recommendation from the

    authentication system analysis.

    '
  success_criteria:
  - MFA enrollment flow for admin users
  - MFA challenge on admin login
  - Recovery codes generated
  - Supabase TOTP properly configured
  why: Security risk - admin accounts lack MFA protection
dependencies: null
handoff:
  format: null
  progress_file: .vest/quickwin-005-progress.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T00:00:00'
  id: QUICKWIN-005
  priority: 1
  template: api-endpoint
  title: Enable MFA for Admin Accounts
on_failure:
  escalate:
    include:
    - error_output
    - partial_implementation
    to: human
  rollback: []
read_first:
- extract: []
  path: lib/auth/index.ts
  reason: Current auth implementation
  required: true
- extract: []
  path: app/(auth)/login/page.tsx
  reason: Current login flow
  required: true
scope:
  constraints: []
  create:
  - components/auth/MFASetup.tsx
  - components/auth/MFAChallenge.tsx
  do_not_touch:
  - supabase/migrations/**
  modify:
  - app/(dashboard)/settings/**
  - lib/auth/**
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
