apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Reduce lint warnings from 295 to under 5 to unblock all future tasks.\n\n\
    WARNING BREAKDOWN (approximate):\n- @typescript-eslint/no-unused-vars: ~140 warnings\n\
    - @typescript-eslint/no-explicit-any: ~20 warnings\n- react-hooks/exhaustive-deps:\
    \ ~15 warnings\n- react/no-unescaped-entities: ~5 warnings\n- Other: ~115 warnings\n\
    \nFIX STRATEGIES:\n\n1. UNUSED VARS (@typescript-eslint/no-unused-vars):\n   -\
    \ If parameter is required by interface but unused: prefix with underscore\n \
    \    Example: `function handler(req, _res)` or `const { used, _unused } = obj`\n\
    \   - If import is unused: remove the import entirely\n   - If variable is truly\
    \ unused: remove the declaration\n\n2. EXPLICIT ANY (@typescript-eslint/no-explicit-any):\n\
    \   - Replace with specific type if known\n   - Use `unknown` if type is truly\
    \ unknown\n   - Use generics where appropriate\n   - For event handlers: `React.MouseEvent<HTMLElement>`\n\
    \n3. REACT HOOKS (react-hooks/exhaustive-deps):\n   - Add missing dependencies\
    \ to dependency array\n   - If intentionally omitting: add eslint-disable comment\
    \ with explanation\n   - Consider useCallback/useMemo for function dependencies\n\
    \n4. UNESCAPED ENTITIES (react/no-unescaped-entities):\n   - Replace \" with &quot;\
    \ or {'\"'}\n   - Replace ' with &apos; or {\"'\"}\n\nIMPORTANT:\n- Do NOT add\
    \ eslint-disable comments unless absolutely necessary\n- Do NOT break existing\
    \ functionality\n- Run typecheck after changes to ensure type safety\n- Focus\
    \ on files with most warnings first\n"
  success_criteria:
  - Lint warnings under 5
  - TypeScript compilation passes
  - Build succeeds
  - No functionality broken
  why: '295 lint warnings blocks ALL task validation (max-warnings 5 policy).

    This technical debt must be cleared to enable feature development.

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T12:30:00'
  id: LINT-CLEANUP-ALL
  priority: 1
  template: code-modification
  title: Fix All Lint Warnings (295 total)
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: lib/dashboard/dashboard-config.ts
  reason: Has many unused vars
  required: true
- extract: []
  path: lib/hooks/usePresence.ts
  reason: Has any types to fix
  required: true
- extract: []
  path: app/(dashboard)/automations/[id]/page.tsx
  reason: Has hook dependency issues
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - node_modules/**
  - .next/**
  - '*.config.*'
  modify:
  - '**/*.ts'
  - '**/*.tsx'
thinking:
  level: think_hard
  triggers:
  - When deciding if eslint-disable is necessary
  - When replacing any types
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 300
