apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Implement contact duplicate detection to prevent data quality issues.


    Features to implement:

    1. Real-time duplicate check during contact creation

    2. Warning dialog when potential duplicate found

    3. Option to view existing contact or continue creating

    4. Match on: email (exact), phone (normalized), name + address combo


    User Flow:

    1. User fills in contact form

    2. On blur of email/phone fields, check for duplicates

    3. If match found, show warning with link to existing contact

    4. User can choose to view existing or continue creating

    '
  success_criteria:
  - Duplicate check fires on email field blur
  - Duplicate check fires on phone field blur
  - Warning dialog shows when duplicate found
  - Dialog links to existing contact
  - User can dismiss warning and continue
  - Backend API endpoint for duplicate checking exists
  why: 'Research Finding: Users are creating duplicate contacts causing data chaos.

    Competitor AccuLynx has intelligent duplicate detection - table stakes feature.


    Business Impact:

    - Sales reps contacting same person multiple times

    - Incorrect reporting due to duplicate data

    - Customer frustration from repeated outreach

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T16:00:00'
  id: SPRINT1-003
  priority: 3
  template: code-modification
  title: Contact Duplicate Detection System
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: components/contacts/contact-form.tsx
  reason: Form to add duplicate checking to
  required: true
- extract: []
  path: app/api/contacts/route.ts
  reason: Understand contact API patterns
  required: true
- extract: []
  path: lib/types/contact.ts
  reason: Contact type definitions
  required: false
scope:
  constraints: []
  create:
  - app/api/contacts/check-duplicate/route.ts
  - components/contacts/DuplicateWarningDialog.tsx
  do_not_touch:
  - app/api/contacts/route.ts
  - lib/validations/contact.ts
  modify:
  - components/contacts/contact-form.tsx
  - app/(dashboard)/contacts/new/page.tsx
thinking:
  level: think_hard
  triggers:
  - Before designing duplicate matching algorithm
  - When deciding API response format
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: test -f app/api/contacts/check-duplicate/route.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: grep -q "DuplicateWarning" components/contacts/contact-form.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
