apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Migrate from pdf-lib (unmaintained for 4 years) to @pdfme/generator

    for PDF generation in the e-signature system. This addresses a critical

    technical debt item identified in the modernization analysis.

    '
  success_criteria:
  - PDF generation works with @pdfme/generator
  - All signature document templates render correctly
  - No visual regressions in generated PDFs
  - pdf-lib removed from dependencies
  why: pdf-lib v1.17.1 hasn't been updated in 4 years - security and maintenance risk
dependencies: null
handoff:
  format: null
  progress_file: .vest/quickwin-003-progress.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T00:00:00'
  id: QUICKWIN-003
  priority: 1
  template: refactor
  title: Migrate pdf-lib to pdfme (Stale Dependency)
on_failure:
  escalate:
    include:
    - error_output
    - migration_notes
    to: human
  rollback:
  - git checkout -- lib/signatures/ package.json package-lock.json
read_first:
- extract: []
  path: lib/signatures/pdf-generator.ts
  reason: Current PDF generation implementation
  required: true
- extract: []
  path: package.json
  reason: Current pdf-lib version
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - supabase/**
  - app/api/** (except signature routes)
  modify:
  - lib/signatures/**
  - package.json
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 60
