apiVersion: aces/v1
changes: []
context:
  background: null
  goal: "Fix 68 TypeScript errors introduced by aggressive lint cleanup.\n\nCOMMON\
    \ ISSUES TO FIX:\n\n1. UNKNOWN TYPE ERRORS:\n   The lint cleanup replaced `any`\
    \ with `unknown` too aggressively.\n   - If accessing properties on unknown: Add\
    \ type assertion or interface\n   - Example: `(data as MyType).property` or proper\
    \ interface\n   - For function params: Use proper parameter types, not unknown\n\
    \n2. BLOCK-SCOPED VARIABLE ERRORS:\n   Variables used before declaration due to\
    \ useCallback refactoring.\n   - Move variable declarations before usage\n   -\
    \ Or restructure the code to avoid circular references\n\n3. TYPE ASSIGNMENT ERRORS:\n\
    \   Incompatible type assignments from Record<string, unknown>.\n   - Replace\
    \ Record<string, unknown> with specific interfaces\n   - Add proper type assertions\
    \ where needed\n\n4. MISSING NAMESPACE ERRORS:\n   JSX namespace issues.\n   -\
    \ Ensure React types are properly imported\n   - Check tsconfig for proper JSX\
    \ settings\n\nFIX STRATEGIES:\n- Restore `any` ONLY if proper typing is genuinely\
    \ complex\n- Prefer specific interfaces over unknown\n- Use type guards for runtime\
    \ type checking\n- Add type assertions with `as Type` syntax\n\nDO NOT:\n- Add\
    \ eslint-disable comments\n- Break existing functionality\n- Create new lint warnings\n"
  success_criteria:
  - npm run typecheck passes with 0 errors
  - npm run lint still passes with 0 warnings
  - npm run build succeeds
  - No functionality broken
  why: 'The lint cleanup reduced warnings from 295 to 0 but introduced 68 TypeScript

    errors. These must be fixed to restore build functionality.

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T13:00:00'
  id: TYPESCRIPT-FIX-POST-LINT
  priority: 1
  template: code-modification
  title: Fix TypeScript Errors from Lint Cleanup
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: app/(dashboard)/automations/[id]/page.tsx
  reason: Has block-scoped variable errors
  required: true
- extract: []
  path: lib/hooks/usePresence.ts
  reason: Has unknown type errors
  required: true
- extract: []
  path: components/bi/QueryResults.tsx
  reason: Has multiple type errors
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - node_modules/**
  - .next/**
  modify:
  - app/(dashboard)/**/*.tsx
  - app/[locale]/(dashboard)/**/*.tsx
  - app/api/**/*.ts
  - components/**/*.tsx
  - lib/**/*.ts
thinking:
  level: think_hard
  triggers:
  - When deciding between any and proper types
  - When fixing complex type assertions
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 0
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 300
