apiVersion: aces/v1
changes: []
context:
  background: 'Bug: Signatures tab shows "failed to fetch sig docs" error when visiting
    /signatures page.


    Needs investigation:

    - Check the signatures page component for the fetch call

    - Trace the API endpoint being called

    - Check for RLS policy issues in Supabase

    - Verify error handling in the API route


    TaskSpec ready at: aces/tasks/SIG-001-fix-signatures-fetch.yaml'
  goal: 'Bug: Signatures tab shows "failed to fetch sig docs" error when visiting
    /signatures page'
  success_criteria:
  - Bug is fixed and no longer reproducible
  - No regressions introduced
  - Test added to prevent regression
  - TypeScript compilation succeeds
  - Linting passes with no warnings
  - Build process completes successfully
  why: 'Needs investigation:

    - Check the signatures page component for the fetch call

    - Trace the API endpoint being called

    - Check for RLS policy issues in Supabase

    - Verify error handling in the API route


    TaskSpec ready at: aces/tasks/SIG-001-fix-signatures-fetch.yaml'
dependencies: null
handoff: null
kind: TaskSpec
metadata:
  archon_task_id: 907fd2a1-9cfe-46cd-9774-306b5b8d30ba
  created: '2025-12-17T23:18:21.515492'
  id: 907FD2A1-FIXSIGNA001
  priority: 5
  template: bug-fix
  title: 'Fix signatures tab error: failed to fetch sig docs'
on_failure: null
read_first:
- extract: []
  path: README.md
  reason: Understanding project structure and conventions
  required: true
- extract: []
  path: '**/*.test.ts'
  reason: Understanding existing test coverage
  required: false
scope:
  constraints:
  - Follow existing code patterns
  - Maintain TypeScript compliance
  - Do not break existing functionality
  create:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  do_not_touch:
  - package.json
  - package-lock.json
  - yarn.lock
  - .git/**
  - node_modules/**
  - dist/**
  - build/**
  modify:
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.js'
  - '**/*.jsx'
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run test
    expect: 'exit_code: 0'
    required: true
    timeout: 300
