apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Validate GPS/Mapping, Property Enrichment, PWA Architecture, Door Knock

    Logging, Photo Capture, and Digital Business Cards. These enable field work.

    '
  success_criteria:
  - PWA migration to @serwist/next validated
  - Offline capabilities assessed
  - Field workflow completeness verified
  why: Mobile/field features critical for door-to-door sales teams
dependencies: null
handoff:
  format: null
  progress_file: .vest/deepdive-progress.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T00:00:00'
  id: DEEPDIVE-005
  priority: 3
  template: research-analysis
  title: 'Modernization Deep Dive: Mobile & Field Features (Modules 18-23)'
on_failure:
  escalate:
    include:
    - partial_findings
    - error_logs
    to: human
  rollback: []
read_first:
- extract: []
  path: docs/modernization-analysis/VALIDATION-REPORT-DEC14.md
  reason: Context from initial validation
  required: true
- extract: []
  path: docs/modernization-analysis/18-MODERNIZATION-GPS-AND-MAPPING.md
  reason: First module in this batch
  required: true
scope:
  constraints: []
  create: []
  do_not_touch: []
  modify: []
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit: []
