apiVersion: aces/v1
changes: []
context:
  background: "## Problem\n\nThe current PDF generation code uses full puppeteer package\
    \ which cannot run on Vercel serverless:\n- Bundled Chromium exceeds function\
    \ size limits\n- Browser persistence pattern does not work in serverless\n- No\
    \ remote Chromium fetching configured\n\n## Current State\n\nFile: lib/pdf/html-to-pdf.ts\n\
    \nUses:\n- import puppeteer from 'puppeteer' (full package ~100MB+)\n- let browser:\
    \ Browser | null = null (persistence pattern)\n- puppeteer.launch() without serverless\
    \ args\n\n## Required Changes\n\n### 1. Install new packages\n\nnpm install @sparticuz/chromium-min@^129.0.0\
    \ puppeteer-core@^23.5.0\n\n### 2. Refactor lib/pdf/html-to-pdf.ts\n\nReplace\
    \ the entire getBrowser function and imports with this serverless-compatible pattern:\n\
    \nimport chromium from '@sparticuz/chromium-min'\nimport puppeteer from 'puppeteer-core'\n\
    \nconst CHROMIUM_PACK_URL = 'https://github.com/Sparticuz/chromium/releases/download/v129.0.0/chromium-v129.0.0-pack.tar'\n\
    \nasync function getBrowser() {\n  return puppeteer.launch({\n    args: [...chromium.args,\
    \ '--hide-scrollbars', '--disable-web-security'],\n    defaultViewport: chromium.defaultViewport,\n\
    \    executablePath: await chromium.executablePath(CHROMIUM_PACK_URL),\n    headless:\
    \ chromium.headless,\n    ignoreHTTPSErrors: true\n  })\n}\n\n### 3. Remove browser\
    \ caching\n\nRemove the let browser: Browser | null = null line and the process.on('exit')\
    \ handler. Each invocation should create a fresh browser.\n\n### 4. Update generatePDFFromHTML\
    \ function\n\nChange from:\n  const browser = await getBrowser()\n  ...\n  await\
    \ page.close()\n\nTo:\n  const browser = await getBrowser()\n  ...\n  await browser.close()\
    \  // Close browser after each use in serverless\n\n## Acceptance Criteria\n\n\
    1. Package @sparticuz/chromium-min is in dependencies\n2. Package puppeteer-core\
    \ is in dependencies\n3. lib/pdf/html-to-pdf.ts uses the serverless pattern\n\
    4. No browser caching (fresh browser per request)\n5. Build passes (npm run build)\n\
    6. TypeScript check passes (npm run typecheck)\n7. Lint passes (npm run lint)\n\
    \n## Important Notes\n\n- The old puppeteer package can remain for local dev (no\
    \ need to remove)\n- Do NOT change any other files\n- Do NOT change the function\
    \ signatures\n- Do NOT add environment detection (the serverless pattern works\
    \ locally too)\n- Test by running: npm run build"
  goal: '## Problem


    The current PDF generation code uses full puppeteer package which cannot run on
    Vercel serverless:

    - Bundled Chromium exceeds function size limits

    - Browser persistence pattern does not work in serverless

    - No remote Chromium fetching configured


    ## Current State


    File: lib/pdf/html-to-pdf.ts


    Uses:

    - import puppeteer from ''puppeteer'' (full package ~100MB+)

    - let browser: Browser | null = null (persistence pattern)

    - puppeteer.launch() without serverless args


    ## Required Changes


    ### 1'
  success_criteria:
  - Bug is fixed and no longer reproducible
  - No regressions introduced
  - Test added to prevent regression
  - TypeScript compilation succeeds
  - Linting passes with no warnings
  - Build process completes successfully
  why: "Install new packages\n\nnpm install @sparticuz/chromium-min@^129.0.0 puppeteer-core@^23.5.0\n\
    \n### 2. Refactor lib/pdf/html-to-pdf.ts\n\nReplace the entire getBrowser function\
    \ and imports with this serverless-compatible pattern:\n\nimport chromium from\
    \ '@sparticuz/chromium-min'\nimport puppeteer from 'puppeteer-core'\n\nconst CHROMIUM_PACK_URL\
    \ = 'https://github.com/Sparticuz/chromium/releases/download/v129.0.0/chromium-v129.0.0-pack.tar'\n\
    \nasync function getBrowser() {\n  return puppeteer.launch({\n    args: [...chromium.args,\
    \ '--hide-scrollbars', '--disable-web-security'],\n    defaultViewport: chromium.defaultViewport,\n\
    \    executablePath: await chromium.executablePath(CHROMIUM_PACK_URL),\n    headless:\
    \ chromium.headless,\n    ignoreHTTPSErrors: true\n  })\n}\n\n### 3. Remove browser\
    \ caching\n\nRemove the let browser: Browser | null = null line and the process.on('exit')\
    \ handler. Each invocation should create a fresh browser. ### 4. Update generatePDFFromHTML\
    \ function\n\nChange from:\n  const browser = await getBrowser()\n  ... await\
    \ page.close()\n\nTo:\n  const browser = await getBrowser()\n  ... await browser.close()\
    \  // Close browser after each use in serverless\n\n## Acceptance Criteria\n\n\
    1. Package @sparticuz/chromium-min is in dependencies\n2. Package puppeteer-core\
    \ is in dependencies\n3. lib/pdf/html-to-pdf.ts uses the serverless pattern\n\
    4. No browser caching (fresh browser per request)\n5. Build passes (npm run build)\n\
    6. TypeScript check passes (npm run typecheck)\n7. Lint passes (npm run lint)\n\
    \n## Important Notes\n\n- The old puppeteer package can remain for local dev (no\
    \ need to remove)\n- Do NOT change any other files\n- Do NOT change the function\
    \ signatures\n- Do NOT add environment detection (the serverless pattern works\
    \ locally too)\n- Test by running: npm run build"
dependencies: null
handoff: null
kind: TaskSpec
metadata:
  archon_task_id: 77387bfb-a8a2-4056-b678-0098cef35ae9
  created: '2025-12-18T22:39:15.712538'
  id: 77387BFB-REFACTOR001
  priority: 5
  template: bug-fix
  title: Refactor PDF generation for Vercel serverless compatibility
on_failure: null
read_first:
- extract: []
  path: README.md
  reason: Understanding project structure and conventions
  required: true
- extract: []
  path: '**/*.test.ts'
  reason: Understanding existing test coverage
  required: false
scope:
  constraints:
  - Follow existing code patterns
  - Maintain TypeScript compliance
  - Do not break existing functionality
  create:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  do_not_touch:
  - package.json
  - package-lock.json
  - yarn.lock
  - .git/**
  - node_modules/**
  - dist/**
  - build/**
  - /Users/ccai/Projects/VEST/**
  - /Users/ccai/Projects/VEST/vest/**
  - /Users/ccai/Projects/VEST/run_aces.py
  - /Users/ccai/Projects/VEST/variants/**
  - /Users/ccai/Projects/VEST/harness/**
  - /Users/ccai/Projects/VEST/SPEC.md
  - /Users/ccai/Projects/VEST/PROTOCOL.md
  modify:
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.js'
  - '**/*.jsx'
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run test
    expect: 'exit_code: 0'
    required: true
    timeout: 300
