apiVersion: aces/v1
changes:
- action: edit
  anchor: null
  description: "Update AdaptiveLayout to conditionally render based on mode:\n\nimport\
    \ { FieldWorkerNav } from './FieldWorkerNav'\nimport { FieldWorkerHome } from\
    \ './FieldWorkerHome'\nimport { Sidebar } from './Sidebar'\n\n// Get current path\
    \ to determine if on dashboard\nconst pathname = usePathname()\nconst isDashboard\
    \ = pathname === '/dashboard' || pathname === '/en/dashboard'\n\nif (mode ===\
    \ 'field') {\n  return (\n    <div className=\"min-h-screen flex flex-col\">\n\
    \      <FieldWorkerNav userEmail={userEmail} />\n      <main className=\"flex-1\"\
    >\n        {isDashboard ? <FieldWorkerHome /> : children}\n      </main>\n   \
    \ </div>\n  )\n}\n\n// Default: full mode with Sidebar\nreturn (\n  <div className=\"\
    min-h-screen flex\">\n    <Sidebar userEmail={userEmail} />\n    <main className=\"\
    flex-1\">{children}</main>\n  </div>\n)\n"
  file: components/layout/AdaptiveLayout.tsx
  position: null
  template: null
- action: create
  anchor: null
  description: 'Create simple pages for field quick actions:


    field/call/page.tsx - renders <QuickCall />

    field/today/page.tsx - renders <TodayView />

    field/me/page.tsx - renders <MyStats />


    Each page is a simple wrapper that imports and renders the component.

    '
  file: app/[locale]/(dashboard)/field/
  position: null
  template: null
- action: edit
  anchor: null
  description: 'Ensure userEmail and userRole are passed down to AdaptiveLayout

    so they can be passed to FieldWorkerNav.

    '
  file: components/layout/DashboardLayoutClient.tsx
  position: null
  template: null
context:
  background: 'P2.1-P2.3 created the components:

    - FieldWorkerHome (4 button interface)

    - FieldWorkerNav (hamburger + drawer)

    - QuickCall, TodayView, MyStats (quick actions)


    Now we need to wire them into AdaptiveLayout so they render when mode=''field''.

    '
  goal: 'Wire up the field worker UI to render based on UI mode. When mode=''field'',

    show FieldWorkerHome on dashboard and use FieldWorkerNav instead of Sidebar.

    '
  success_criteria:
  - AdaptiveLayout conditionally renders FieldWorkerNav when mode='field'
  - Dashboard route shows FieldWorkerHome when mode='field'
  - Other routes in field mode show FieldWorkerNav + page content
  - mode='full' still shows Sidebar as before
  - ARIA bar remains visible in all modes
  - TypeScript compiles without errors
  - Lint passes
  - Build succeeds
  why: 'Without this integration, the field worker components exist but never render.

    This task completes the field mode experience.

    '
dependencies:
  blocks:
  - ADAPTIVE-UI-P2-5
  requires:
  - ADAPTIVE-UI-P2-1
  - ADAPTIVE-UI-P2-2
  - ADAPTIVE-UI-P2-3
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
kind: TaskSpec
metadata:
  archon_task_id: 5c0f280d-1d3b-4fef-8045-bbd61d2f5155
  created: null
  id: ADAPTIVE-UI-P2-4
  priority: 1
  template: code-modification
  title: Integrate field mode with routing and layout
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git checkout -- .
read_first:
- extract: []
  path: components/layout/AdaptiveLayout.tsx
  reason: Main file to modify for conditional rendering
  required: true
- extract: []
  path: components/layout/DashboardLayoutClient.tsx
  reason: Understand current layout structure
  required: true
- extract: []
  path: components/layout/FieldWorkerHome.tsx
  reason: Component to render in field mode
  required: true
- extract: []
  path: components/layout/FieldWorkerNav.tsx
  reason: Nav component for field mode
  required: true
scope:
  constraints: []
  create:
  - app/[locale]/(dashboard)/field/call/page.tsx
  - app/[locale]/(dashboard)/field/today/page.tsx
  - app/[locale]/(dashboard)/field/me/page.tsx
  do_not_touch:
  - components/ai-assistant/**
  - app/api/**
  - lib/ui-mode/**
  modify:
  - components/layout/AdaptiveLayout.tsx
  - components/layout/DashboardLayoutClient.tsx
thinking:
  level: think
  triggers:
  - When handling route detection
  - When deciding component nesting
validation:
  assertions:
  - contains: []
    context: any
    description: ''
    file: components/layout/AdaptiveLayout.tsx
    not_contains: []
    regex_match: []
    required: true
  - contains: []
    context: any
    description: ''
    file: components/layout/AdaptiveLayout.tsx
    not_contains: []
    regex_match: []
    required: true
  - contains: []
    context: any
    description: ''
    file: app/[locale]/(dashboard)/field/call/page.tsx
    not_contains: []
    regex_match: []
    required: true
  post_commit: []
  pre_commit:
  - command: cd "/Users/ccai/Roofing SaaS/roofing-saas" && npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: cd "/Users/ccai/Roofing SaaS/roofing-saas" && npm run lint -- --max-warnings
      5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: cd "/Users/ccai/Roofing SaaS/roofing-saas" && npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 180
