apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Implement a project templates system with roofing-specific workflow templates

    for faster, more consistent project creation.


    Features to implement:

    1. Pre-built roofing project templates

    2. Custom template creation from existing projects

    3. Automated task and milestone generation from template

    4. Template library management

    5. Template versioning and updates


    Default Templates:

    - Residential Roof Replacement

    - Commercial Roof Installation

    - Storm Damage Repair

    - Roof Inspection

    - Insurance Claim Project

    - Emergency Repair


    Template Contents:

    - Default project stages

    - Pre-populated tasks with estimated durations

    - Milestone definitions

    - Document checklist

    - Default team assignments

    '
  success_criteria:
  - Can select template when creating new project
  - Template populates stages, tasks, and milestones
  - Can create custom template from existing project
  - Template library is manageable
  - Template applies correctly to new projects
  why: 'Research Finding: Every project created from scratch.

    Competitor JobNimbus has roofing-specific templates.


    Business Impact:

    - 50% faster project setup

    - 30% more consistent execution

    - Reduced training time for new users

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T19:00:00'
  id: SPRINT3-003
  priority: 2
  template: code-modification
  title: Project Templates System
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: components/projects/project-form.tsx
  reason: Project creation form to add template selection
  required: true
- extract: []
  path: lib/types/project.ts
  reason: Project type definitions
  required: true
- extract: []
  path: app/(dashboard)/projects/new/page.tsx
  reason: New project page flow
  required: true
scope:
  constraints: []
  create:
  - lib/types/project-template.ts
  - components/projects/TemplateSelector.tsx
  - components/projects/TemplateLibrary.tsx
  - components/projects/TemplateEditor.tsx
  - app/(dashboard)/settings/templates/page.tsx
  - app/api/project-templates/route.ts
  - app/api/project-templates/[id]/route.ts
  - lib/data/default-templates.ts
  do_not_touch:
  - app/api/projects/route.ts
  - lib/validations/project.ts
  modify:
  - app/(dashboard)/projects/new/page.tsx
  - components/projects/project-form.tsx
thinking:
  level: think_hard
  triggers:
  - Before designing template data structure
  - When planning template-to-project mapping
  - When designing default templates
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/types/project-template.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/projects/TemplateSelector.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/data/default-templates.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
