apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Enhance the file management system with centralized document organization.


    Features to implement:

    1. File categorization system (contracts, photos, permits, invoices, etc.)

    2. Folder hierarchy for organizing files within projects

    3. File search and filtering capabilities

    4. File versioning support (track file history)

    5. Bulk file operations (select multiple, move, delete)

    6. Mobile-optimized file upload with photo capture


    File Categories for Roofing:

    - Contracts & Agreements

    - Photos (before/during/after)

    - Permits & Inspections

    - Invoices & Estimates

    - Insurance Documents

    - Warranty Documents

    - Material Specs

    - Other


    NOTE: Build on existing project-files infrastructure.


    IMPORTANT CODE QUALITY REQUIREMENTS:

    - Run `npm run typecheck` and fix ALL errors before completing

    - Run `npm run lint` and fix errors, keep warnings under 10

    - Do NOT create duplicate type definitions

    - Import all types you use (FileType, RoofingFileCategory, etc.)

    - Do NOT use `any` type - use proper types or `unknown`

    - Prefix unused parameters with underscore: `_param`

    - Use theme variables, not hardcoded colors

    '
  success_criteria:
  - Files can be categorized
  - Folder structure supported
  - Search/filter works on files
  - Version history accessible
  - Mobile upload functional
  - Bulk operations work
  why: 'Research Finding: No centralized document organization causes project chaos.

    Competitor Buildertrend provides complete document management.


    Business Impact:

    - Projects lose critical documents

    - No version control on contracts

    - Field teams can''t access files on mobile

    - Compliance risk from missing documentation

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T18:00:00'
  id: SPRINT2-002
  priority: 2
  template: code-modification
  title: File Management System Core Features
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: components/project-files/project-files-table.tsx
  reason: Existing file table to enhance
  required: true
- extract: []
  path: components/project-files/project-file-form.tsx
  reason: Existing upload form to enhance
  required: true
- extract: []
  path: app/api/project-files/route.ts
  reason: Existing file API patterns
  required: true
scope:
  constraints: []
  create:
  - lib/types/file.ts
  - components/project-files/FileCategories.tsx
  - components/project-files/FileFolderTree.tsx
  - components/project-files/FileVersionHistory.tsx
  - components/project-files/BulkFileActions.tsx
  - components/project-files/MobileFileUpload.tsx
  - app/api/project-files/versions/route.ts
  - app/api/project-files/search/route.ts
  do_not_touch:
  - storage bucket configurations
  - Supabase storage policies
  modify:
  - components/project-files/project-files-table.tsx
  - components/project-files/project-file-form.tsx
  - app/api/project-files/route.ts
  - app/api/project-files/[id]/route.ts
thinking:
  level: think_hard
  triggers:
  - Before designing folder hierarchy structure
  - When implementing file versioning
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/types/file.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: grep -q "FileCategories" components/project-files/project-files-table.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/project-files/MobileFileUpload.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
