apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Fix the 404 error when clicking "Edit Project" from the project detail page.


    Bug Report:

    - Page: /pipeline

    - Action: Click on project name to open detail, then click "Edit Project"

    - Error: 404 page not found


    Investigation Steps:

    1. Find the Edit Project button/link in project detail

    2. Check the href/route it navigates to

    3. Verify the edit page route exists

    4. Fix routing or create missing page

    '
  success_criteria:
  - Edit Project button navigates to edit form
  - Edit form loads and displays project data
  - No 404 error
  why: 'Users cannot edit projects, blocking a core workflow.

    This is a critical navigation bug.

    '
dependencies: null
handoff: null
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T00:00:00'
  id: BUG-004
  priority: 2
  template: bug-fix
  title: 'Fix: Edit Project 404 error'
on_failure: null
read_first:
- extract: []
  path: app/(dashboard)/projects/[id]/page.tsx
  reason: Find Edit Project button
  required: true
- extract: []
  path: app/(dashboard)/pipeline/page.tsx
  reason: Check pipeline navigation
  required: false
scope:
  constraints: []
  create:
  - app/(dashboard)/projects/[id]/edit/page.tsx
  do_not_touch:
  - lib/supabase/server.ts
  modify:
  - app/(dashboard)/projects/[id]/**/*.tsx
  - app/(dashboard)/pipeline/**/*.tsx
thinking:
  level: think
  triggers:
  - When tracing navigation flow
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
