apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Implement a professional multi-option quoting system with Good/Better/Best

    proposal options for roofing estimates.


    Features to implement:

    1. Quote templates with multiple pricing tiers

    2. Good/Better/Best option presentation

    3. Professional proposal PDF generation

    4. E-signature integration (using existing DocuSign/similar)

    5. Quote tracking and analytics


    User Experience:

    - Create estimate with multiple material/scope options

    - Professional proposal view for customers

    - Easy comparison between options

    - One-click to send for signature


    Quote Structure:

    - Option name (Good/Better/Best or custom)

    - Itemized line items per option

    - Option-specific totals

    - Recommended option highlighting

    '
  success_criteria:
  - Can create estimate with 2-3 pricing options
  - Options display in professional comparison view
  - PDF export shows all options professionally
  - Customer can select preferred option
  - Quote status tracking works
  why: 'Research Finding: Single estimate only, not professional.

    Competitor AccuLynx offers Good/Better/Best proposal options.


    Business Impact:

    - 25% increase in average deal size

    - Professional presentation increases close rate

    - Upselling opportunities with tiered options

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T19:00:00'
  id: SPRINT3-002
  priority: 2
  template: code-modification
  title: Multi-Option Quoting System
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: components/estimates/estimate-form.tsx
  reason: Existing estimate form to enhance
  required: true
- extract: []
  path: lib/types/estimate.ts
  reason: Estimate type definitions
  required: true
- extract: []
  path: app/(dashboard)/estimates/[id]/page.tsx
  reason: Estimate detail page to add options view
  required: true
scope:
  constraints: []
  create:
  - lib/types/quote-option.ts
  - components/estimates/QuoteOptions.tsx
  - components/estimates/QuoteOptionCard.tsx
  - components/estimates/QuoteComparison.tsx
  - components/estimates/QuoteProposalView.tsx
  - app/api/estimates/[id]/options/route.ts
  do_not_touch:
  - app/api/estimates/route.ts
  - lib/validations/estimate.ts
  modify:
  - components/estimates/estimate-form.tsx
  - app/(dashboard)/estimates/[id]/page.tsx
thinking:
  level: think_hard
  triggers:
  - Before designing quote option data model
  - When planning PDF generation approach
  - When designing comparison UI
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f lib/types/quote-option.ts
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: test -f components/estimates/QuoteOptions.tsx
    expect: 'exit_code: 0'
    required: true
    timeout: 60
