apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Fix the "Signature document not found not found" error displayed

    on the signatures page when clicking on a document.


    Steps:

    1. Document the bug - reproduce and capture error details

    2. Investigate root cause - trace through signatures page code

    3. Plan fix - identify what needs to change

    4. Implement fix - make necessary code changes

    5. Validate - ensure fix works and doesn''t break other functionality

    '
  success_criteria:
  - Bug is documented with reproduction steps
  - Root cause is identified
  - Fix is implemented and tested
  - Error message is properly formatted if document not found
  why: 'User reports error when clicking documents on signatures page.

    Error message shows ''not found'' duplicated - ''Signature document not found
    not found''.

    This is a user-facing bug that needs immediate attention.

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-15T01:35:00'
  id: BUG-001
  priority: 2
  template: bug-fix
  title: Fix Signature Document Not Found Error
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: app/(dashboard)/signatures/page.tsx
  reason: Main signatures page to understand error source
  required: true
- extract: []
  path: components/signatures/SignatureDocuments.tsx
  reason: Document list component
  required: true
- extract: []
  path: app/api/signatures/documents/[id]/route.ts
  reason: API endpoint for document fetch
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - lib/supabase/server.ts
  modify:
  - app/(dashboard)/signatures/page.tsx
  - components/signatures/SignatureDocuments.tsx
  - app/api/signatures/documents/route.ts
  - app/api/signatures/documents/[id]/route.ts
thinking:
  level: think_hard
  triggers:
  - When identifying error source
  - Before implementing fix
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 60
