apiVersion: aces/v1
changes:
- action: edit
  anchor: null
  description: '1. Rename the territories/ folder to knocks/

    2. Create new territories/page.tsx that redirects to /knocks

    3. Update any [id] or new subdirectories accordingly

    '
  file: app/[locale]/(dashboard)/
  position: null
  template: null
- action: edit
  anchor: null
  description: "Replace navSections with new 4-group structure:\n\nSELL (6 items):\
    \ Knock, Signatures, Claims, Incentives, Lead Gen, Storm Intel\nCORE (5 items):\
    \ Dashboard, Pipeline, Business Intel, Events, Tasks\nCOMMUNICATIONS (2 items):\
    \ Call Log, Messages\nSETTINGS (1 item): Settings\n\nREMOVE: Voice AI (/voice-assistant)\
    \ and Campaigns (/campaigns)\nRENAME: Field Activity \u2192 Knock, href /territories\
    \ \u2192 /knocks\n"
  file: components/layout/Sidebar.tsx
  position: null
  template: null
- action: edit
  anchor: null
  description: Find and replace all /territories links with /knocks
  file: '**/*.tsx'
  position: null
  template: null
context:
  background: 'The owner requested a nav reorganization to better match the sales
    workflow.

    "Knock" is roofing industry slang for door-to-door canvassing.

    Voice AI and Campaigns are being removed from nav (accessible via other means).

    '
  goal: 'Reorganize the sidebar navigation into 4 logical groups (Sell, Core, Communications,
    Settings)

    and rename the /territories route to /knocks.

    '
  success_criteria:
  - Route /knocks works and shows the territories/field activity page
  - Route /territories redirects to /knocks
  - 'Sidebar shows 4 groups: SELL, CORE, COMMUNICATIONS, SETTINGS'
  - Nav has 14 items total (Voice AI and Campaigns removed)
  - All internal links updated from /territories to /knocks
  - TypeScript compiles without errors
  - Lint passes
  - Build succeeds
  why: 'Current nav has 16 items across 4 arbitrary groups. New structure groups by
    job-to-be-done:

    - SELL: Revenue-generating activities

    - CORE: Business operations

    - COMMUNICATIONS: Customer touchpoints

    - SETTINGS: Configuration

    '
dependencies:
  blocks: []
  requires: []
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
kind: TaskSpec
metadata:
  archon_task_id: ccedf3c3-c3f5-4cfb-ae15-50a6707b12a6
  created: null
  id: NAV-REORG-001
  priority: 1
  template: code-modification
  title: Reorganize sidebar navigation + rename territories to knocks
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git checkout -- .
read_first:
- extract: []
  path: components/layout/Sidebar.tsx
  reason: Current nav structure to replace
  required: true
- extract: []
  path: app/[locale]/(dashboard)/territories/page.tsx
  reason: Main page to move to /knocks
  required: true
- extract: []
  path: app/[locale]/(dashboard)/knocks/page.tsx
  reason: Current redirect to reverse
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - components/ai-assistant/**
  - lib/**
  - app/api/**
  modify:
  - components/layout/Sidebar.tsx
  - app/[locale]/(dashboard)/knocks/
  - app/[locale]/(dashboard)/territories/
thinking:
  level: think
  triggers:
  - When deciding order of operations
  - If encountering unexpected file structures
validation:
  assertions:
  - contains: []
    context: any
    description: ''
    file: app/[locale]/(dashboard)/knocks/page.tsx
    not_contains: []
    regex_match: []
    required: true
  - contains: []
    context: any
    description: ''
    file: components/layout/Sidebar.tsx
    not_contains: []
    regex_match: []
    required: true
  - contains: []
    context: any
    description: ''
    file: components/layout/Sidebar.tsx
    not_contains: []
    regex_match: []
    required: true
  post_commit: []
  pre_commit:
  - command: cd "/Users/ccai/Roofing SaaS/roofing-saas" && npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: cd "/Users/ccai/Roofing SaaS/roofing-saas" && npm run lint -- --max-warnings
      5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: cd "/Users/ccai/Roofing SaaS/roofing-saas" && npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 180
