apiVersion: aces/v1
changes: []
context:
  background: 'Tech stack:

    - Next.js 15 with App Router

    - Node.js (check package.json for version)

    - npm for package management

    - TypeScript

    - ESLint with custom rules

    '
  goal: Create GitHub Actions CI/CD workflow for automated testing
  success_criteria:
  - GitHub Actions workflow file exists at .github/workflows/ci.yml
  - Workflow runs on PR and push to main
  - 'Workflow includes: lint, typecheck, build'
  - Workflow includes npm audit for security
  - Build passes with new workflow file
  why: 'Currently only local pre-commit hooks exist. No automated testing on:

    - Pull requests

    - Main branch pushes

    - Scheduled security audits


    This creates risk of broken code being merged and security issues going undetected.

    '
dependencies:
  blocks: []
  requires: []
handoff: null
kind: TaskSpec
metadata:
  archon_task_id: e69f1b56-7649-48bb-929b-1a1a70cb1dc6
  created: null
  id: CICD-001
  priority: 2
  template: null
  title: '[P2] Create CI/CD Workflow'
on_failure:
  escalate:
    include:
    - error_output
    to: human
  rollback:
  - rm -f .github/workflows/ci.yml
read_first:
- extract: []
  path: package.json
  reason: Understand available scripts and Node version
  required: true
- extract: []
  path: .nvmrc
  reason: Check for specific Node version requirement
  required: false
scope:
  constraints:
  - Use GitHub Actions syntax
  - Use npm, not yarn or pnpm
  - Include caching for node_modules
  - Fail fast on errors
  create:
  - .github/workflows/ci.yml
  do_not_touch:
  - app/**
  - lib/**
  - components/**
  - supabase/**
  - next.config.ts
  modify: []
thinking:
  level: think
  triggers:
  - When designing workflow structure
  - When configuring caching
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: cd /Users/ccai/Roofing\ SaaS/roofing-saas && test -f .github/workflows/ci.yml
      && echo 'exists'
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: cd /Users/ccai/Roofing\ SaaS/roofing-saas && npm run build
    expect: 'exit_code: 0'
    required: true
    timeout: 60
