apiVersion: aces/v1
changes:
- action: create
  anchor: null
  description: Seed file with 11 industry-standard templates
  file: supabase/seeds/signature-templates.sql
  position: null
  template: null
context:
  background: 'Templates needed (Full Suite):


    Insurance Restoration:

    1. Authorization of Insured (AOB/Contingency Agreement) - CRITICAL

    2. Insurance Work Completion Certificate

    3. Authorization to Release Insurance Information


    Core Roofing:

    4. Residential Roofing Contract

    5. Change Order

    6. Conditional Lien Release (Progress Payment)

    7. Unconditional Lien Release (Final Payment)

    8. Limited Workmanship Warranty

    9. Completion Certificate / Customer Approval


    Inspection:

    10. Pre-Roofing Inspection Form

    11. Roof Inspection Report


    Research industry-standard language for each document.

    The document_templates table exists with these columns:

    id, tenant_id, created_by, name, description, category,

    html_content, pdf_template_url, signature_fields (JSONB),

    is_active, requires_customer_signature, requires_company_signature,

    expiration_days

    '
  goal: Create 11 industry-standard signature templates for roofing contractors
  success_criteria:
  - 11 templates created in seed file
  - Each template has name, description, category, signature_fields, requires_customer_signature,
    requires_company_signature, expiration_days
  - Templates follow legal and industry standards for roofing
  - Seed file can be executed against Supabase
  - Templates appear in UI after seeding
  why: 'The signatures feature has no starter templates. Roofing contractors need

    industry-standard documents to be productive immediately. This is especially

    important for Appalachian Storm Restoration (insurance restoration focus).

    '
dependencies: null
handoff: null
kind: TaskSpec
metadata:
  archon_task_id: 2994b00a-adfb-4d6b-b185-2d384d6d13e0
  created: '2025-12-18T03:20:00'
  id: SIG-002-TEMPLATES
  priority: 5
  template: feature
  title: Create Full Suite signature templates
on_failure: null
read_first:
- extract: []
  path: supabase/migrations/*signature*
  reason: Understanding signature tables schema
  required: true
- extract: []
  path: components/signatures/FieldPalette.tsx
  reason: Understanding available field types
  required: true
scope:
  constraints:
  - Use realistic legally-appropriate language for contracts
  - signature_fields should include reasonable default field placements
  - Templates should be tenant-agnostic (can work for any tenant)
  - Use category values from contract, estimate, change_order, waiver, other
  create:
  - supabase/seeds/signature-templates.sql
  do_not_touch:
  - supabase/migrations/**
  - package.json
  - .git/**
  - node_modules/**
  modify: []
thinking: null
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 5
    expect: 'exit_code: 0'
    required: true
    timeout: 60
