apiVersion: aces/v1
changes: []
context:
  background: null
  goal: 'Standardize UI patterns across the application for consistency and maintainability.


    Phase 1 Focus Areas:

    1. Replace all hardcoded colors with theme variables

    2. Standardize loading states with skeleton components

    3. Create consistent empty state patterns

    4. Standardize form layouts (spacing, labels, errors)

    5. Ensure all buttons use the shadcn/ui Button component


    Patterns to Enforce:

    - NO hardcoded colors (bg-white, text-gray-500, etc.)

    - Use bg-background, bg-card, text-foreground, text-muted-foreground

    - Use border-border instead of border-gray-*

    - All interactive elements use shadcn components


    Key Files to Audit:

    - Dashboard components

    - Settings pages

    - Pipeline views

    - Any pages with inline styles


    DO NOT BREAK EXISTING FUNCTIONALITY. Only change styling, not behavior.

    '
  success_criteria:
  - No hardcoded color classes in components
  - Skeleton loading states in list views
  - Empty states for all list components
  - Form layouts follow consistent pattern
  - All buttons use Button component
  why: 'Research Finding: Mixed component patterns create maintenance nightmare.

    Technical debt accumulating with multiple implementation patterns.


    Problems:

    - Inconsistent visual appearance across modules

    - Dark mode support impossible with hardcoded colors

    - Difficult to maintain and update styles

    - Poor developer experience

    '
dependencies: null
handoff:
  format: null
  progress_file: .vest/last_run_summary.md
  update_on:
  - task_start
  - task_complete
  - failure
kind: TaskSpec
metadata:
  archon_task_id: null
  created: '2025-12-14T18:00:00'
  id: SPRINT2-003
  priority: 2
  template: code-modification
  title: UI Consistency Standardization Phase 1
on_failure:
  escalate:
    include:
    - error_output
    - files_modified
    to: human
  rollback:
  - git stash
read_first:
- extract: []
  path: components/ui/button.tsx
  reason: Standard button component to use
  required: true
- extract: []
  path: components/territories/TerritoryMapDirect.tsx
  reason: Has 6 hardcoded colors - highest priority
  required: true
- extract: []
  path: components/projects/TemplateSelector.tsx
  reason: Has 4 hardcoded colors - high priority
  required: true
scope:
  constraints: []
  create: []
  do_not_touch:
  - components/ui/button.tsx
  - components/ui/input.tsx
  - components/ui/select.tsx
  - lib/validations/**
  - app/api/**
  modify:
  - components/territories/TerritoryMapDirect.tsx
  - components/territories/TerritoryMapClient.tsx
  - components/projects/TemplateSelector.tsx
  - components/projects/TemplateLibrary.tsx
  - components/tasks/TasksList.tsx
  - components/substatus/SubstatusBadge.tsx
  - components/storm/StormResponseMode.tsx
  - components/knocks/KnockLogger.tsx
  - components/automation/WorkflowCanvas.tsx
  - components/analytics/ConversionFunnel.tsx
  - components/admin/AuditLogsTable.tsx
  - components/voice/VoiceDiagnostics.tsx
  - components/ui/switch.tsx
  - components/territories/PinPopup.tsx
  - components/project-files/FileVersionHistory.tsx
thinking:
  level: think_hard
  triggers:
  - Before establishing pattern for skeleton states
  - When deciding empty state design
validation:
  assertions: []
  post_commit: []
  pre_commit:
  - command: npm run typecheck
    expect: 'exit_code: 0'
    required: true
    timeout: 120
  - command: npm run lint -- --max-warnings 0
    expect: 'exit_code: 0'
    required: true
    timeout: 60
  - command: '! grep -rE ''bg-white|bg-gray-|text-gray-|border-gray-'' components/territories/
      components/projects/ --include=''*.tsx'' 2>/dev/null | head -1'
    expect: 'exit_code: 0'
    required: true
    timeout: 30
