import { test, expect } from '@playwright/test'
import path from 'path'
import fs from 'fs'
import { createTestImage, cleanupTestImages } from './fixtures/test-images'

const TEST_IMAGE_DIR = path.join(__dirname, 'fixtures', 'generated')
const TEST_IMAGE_PATH = path.join(TEST_IMAGE_DIR, 'test-thumbnail.png')

test.describe('Project Files - Thumbnail Generation', () => {
  test.use({ storageState: 'playwright/.auth/user.json' })

  let testContactId: string | null = null

  test.beforeAll(async () => {
    await createTestImage(TEST_IMAGE_PATH)
  })

  test.afterAll(async () => {
    await cleanupTestImages(TEST_IMAGE_DIR)
  })

  // Get a valid contact_id for the test tenant (required by DB constraint)
  test.beforeEach(async ({ page }) => {
    if (!testContactId) {
      const res = await page.request.get('/api/contacts?limit=1')
      if (res.ok()) {
        const body = await res.json()
        const contacts = body.data?.contacts ?? body.contacts ?? body.data ?? []
        if (contacts.length > 0) {
          testContactId = contacts[0].id
        }
      }
    }
    test.skip(!testContactId, 'No contacts in test tenant — cannot create files (DB constraint)')
  })

  test('image upload produces a thumbnail_url', async ({ page }) => {
    const imageBuffer = fs.readFileSync(TEST_IMAGE_PATH)

    const response = await page.request.post('/api/project-files/upload', {
      multipart: {
        file: {
          name: 'test-thumbnail-upload.png',
          mimeType: 'image/png',
          buffer: imageBuffer,
        },
        file_name: 'E2E Thumbnail Test',
        file_type: 'photo',
        file_category: 'photos-damage',
        contact_id: testContactId!,
      },
    })

    expect(response.ok(), `Upload failed: ${response.status()}`).toBe(true)

    const body = await response.json()
    const file = body.data?.file ?? body.file

    expect(file).toBeTruthy()
    expect(file.file_url).toBeTruthy()
    expect(file.mime_type).toBe('image/png')

    // Thumbnail was generated by sharp and stored
    expect(file.thumbnail_url).toBeTruthy()
    expect(file.thumbnail_url).toContain('/thumbs/')
    expect(file.thumbnail_url).not.toBe(file.file_url)

    // Thumbnail URL should be a valid URL pointing to storage
    expect(file.thumbnail_url).toMatch(/^https?:\/\//)
    expect(file.thumbnail_url).toContain('.jpg')

    // Clean up
    if (file.id) {
      await page.request.delete(`/api/project-files/${file.id}`)
    }
  })

  test('non-image upload returns null thumbnail_url', async ({ page }) => {
    const textContent = Buffer.from('Test document for thumbnail verification.')

    const response = await page.request.post('/api/project-files/upload', {
      multipart: {
        file: {
          name: 'test-no-thumb.txt',
          mimeType: 'text/plain',
          buffer: textContent,
        },
        file_name: 'E2E No Thumbnail Test',
        file_type: 'document',
        file_category: 'other',
        contact_id: testContactId!,
      },
    })

    expect(response.ok(), `Upload failed: ${response.status()}`).toBe(true)

    const body = await response.json()
    const file = body.data?.file ?? body.file

    expect(file).toBeTruthy()
    expect(file.thumbnail_url).toBeNull()

    // Clean up
    if (file.id) {
      await page.request.delete(`/api/project-files/${file.id}`)
    }
  })

  test('thumbnail_url and file_url use different storage paths', async ({ page }) => {
    const imageBuffer = fs.readFileSync(TEST_IMAGE_PATH)

    const response = await page.request.post('/api/project-files/upload', {
      multipart: {
        file: {
          name: 'test-path-check.png',
          mimeType: 'image/png',
          buffer: imageBuffer,
        },
        file_name: 'E2E Path Check',
        file_type: 'photo',
        file_category: 'photos-after',
        contact_id: testContactId!,
      },
    })

    expect(response.ok()).toBe(true)
    const body = await response.json()
    const file = body.data?.file ?? body.file

    // Original goes to project-files/, thumbnail goes to project-files/thumbs/
    expect(file.file_url).toContain('/project-files/')
    expect(file.file_url).not.toContain('/thumbs/')
    expect(file.thumbnail_url).toContain('/project-files/thumbs/')

    // Both should share the same base filename pattern (timestamp_random)
    const originalName = file.file_url.split('/').pop()?.replace(/\.[^.]+$/, '')
    const thumbName = file.thumbnail_url.split('/').pop()?.replace(/\.[^.]+$/, '')
    expect(thumbName).toBe(originalName)

    // Clean up
    if (file.id) {
      await page.request.delete(`/api/project-files/${file.id}`)
    }
  })
})
